### ISSUE TITLE
Consolidate SWAP code (matswap/swap) to work with new db interface

### ISSUE THREAD

**Issue by marco-willi** [zooniverse/hco-experiments#5]
There is a first version of the consolidated swap code in the branch 'upgrade_branch'. It includes a test-file 'swap_test.py' which can be used to processes the whole db of classifications.

Open Tasks:
- implement save functionality
- implement a method in 'server.py' to be used in 'swap.py'
- implement new modules agent/subject/... to simplify the code, analog to the original SWAP implementation (see Michaels comment in code),
- test/compare new version with old one

My questions:
- Should we merge the new version with the master branch and work from there?
- Should we further modularize the code with classes for agents, etc... ? (I'd vote in favour of it, because it simplifies the code, I'd however first try to verify the current implementation)

**Comment by miclaraia** [comment]
I started working on the agent class. I'm also working on a Prob_Tracker class that will keep track of the history, let me know what you think.

Also, Marco, do you remember the details of what we were discussing last Friday? I wanted to mention it to Darryl but couldn't recall the details in the moment. Might be good to put that to paper so we can reference it later.

**Comment by marco-willi** [comment]
Some things we discussed:
- how important is it to process classifications in temporal order (for experiments, for pre-processing), I have the impression that this is necessary for the experiments at least, that question obviously affects how effectively we can query the db (one classification at a time or one user/subject at a time).
- Implementation of SWAP such that it queries the database to obtain the agent/confusion matrix of a new user, after that the users' data is kept in memory (agent class) and written back to the db when we assume that the user is finished (not sure that question is relevant for a non-live situation)
- we also briefly touched upon how to conduct experiments and how to prepare the data for it but I think that's something we need to discuss with Darryl

**Comment by miclaraia** [comment]
Right, because I was thinking about aggregating the data and processing all the users first, and then the subjects, but then that wouldn't work because everything has to be calculated in the order it comes in for the experiments.

**Comment by miclaraia** [comment]
About working from the master branch... Yeah I think that's a good idea, at least for now. Once we have a working version to do experiments with I think we should make new branches for improvements, and have lucifer running code off the master branch.
