### ISSUE TITLE
SWAP updates to the subject probability are incorrect when the annotation is ‘1’.

### ISSUE THREAD

**Issue by dwright04** [zooniverse/hco-experiments#6]
The updated implementation of SWAP does not correctly calculate the Subject probability when a user submits an annotation of ‘1’.  This [line](https://github.com/zooniverse/hco-experiments/blob/master/swap/swap/swap.py#L161) is missing a factor (1-sub_pos) from the denominator.  The current implementation fails the test_subject_update_apply_one_correct_classification() test in test_swap.py.  Replacing the subject probability update with:

`sub_pos_new = sub_times_user / (sub_times_user + (1-user_fail) * (1-sub_pos))`

fixes the issue.

**Comment by marco-willi** [comment]
Argh, thanks for pointing that out. We actually corrected that in the new SWAP version but I forgot to update it in swap.py. It is corrected now!
